%macro edw_linking_cleaner_addr(prefix);
if &prefix.address1 ne '' then do;

&prefix.address1=upcase(&prefix.address1);
&prefix.address1=tranwrd(&prefix.address1," ALLEY"," ALY");
&prefix.address1=tranwrd(&prefix.address1," ANNEX"," ANX");
&prefix.address1=tranwrd(&prefix.address1," ARCADE"," ARC");
&prefix.address1=tranwrd(&prefix.address1," AVENUE"," AVE");
&prefix.address1=tranwrd(&prefix.address1," BAYOU"," BYU");
&prefix.address1=tranwrd(&prefix.address1," BEACH"," BCH");
&prefix.address1=tranwrd(&prefix.address1," BEND"," BND");
&prefix.address1=tranwrd(&prefix.address1," BLUFF"," BLF");
&prefix.address1=tranwrd(&prefix.address1," BOTTOM"," BTM");
&prefix.address1=tranwrd(&prefix.address1," BOULEVARD"," BLVD");
&prefix.address1=tranwrd(&prefix.address1," BRANCH"," BR");
&prefix.address1=tranwrd(&prefix.address1," BRIDGE"," BRG");
&prefix.address1=tranwrd(&prefix.address1," BROOK"," BRK");
&prefix.address1=tranwrd(&prefix.address1," BURG"," BG");
&prefix.address1=tranwrd(&prefix.address1," BYPASS"," BYP");
&prefix.address1=tranwrd(&prefix.address1," CAMP"," CP");
&prefix.address1=tranwrd(&prefix.address1," CANYON"," CYN");
&prefix.address1=tranwrd(&prefix.address1," CAPE"," CPE");
&prefix.address1=tranwrd(&prefix.address1," CAUSEWAY"," CWSY");
&prefix.address1=tranwrd(&prefix.address1," CENTER"," CTR");
&prefix.address1=tranwrd(&prefix.address1," CIRCLE"," CIR");
&prefix.address1=tranwrd(&prefix.address1," CLIFFS"," CLFS");
&prefix.address1=tranwrd(&prefix.address1," CLUB"," CLB");
&prefix.address1=tranwrd(&prefix.address1," CORNER"," COR");
&prefix.address1=tranwrd(&prefix.address1," COURSE"," CRSE");
&prefix.address1=tranwrd(&prefix.address1," COURT"," CT");
&prefix.address1=tranwrd(&prefix.address1," COVE"," CV");
&prefix.address1=tranwrd(&prefix.address1," CREEK"," CRK");
&prefix.address1=tranwrd(&prefix.address1," CRESCENT"," CRES");
&prefix.address1=tranwrd(&prefix.address1," CROSSING"," XING");
&prefix.address1=tranwrd(&prefix.address1," DALE"," DL");
&prefix.address1=tranwrd(&prefix.address1," DAM"," DM");
&prefix.address1=tranwrd(&prefix.address1," DIVIDE"," DV");
&prefix.address1=tranwrd(&prefix.address1," DRIVE"," DR");
&prefix.address1=tranwrd(&prefix.address1," ESTATES"," EST");
&prefix.address1=tranwrd(&prefix.address1," EXPRESSWAY"," EXPY");
&prefix.address1=tranwrd(&prefix.address1," EXTENSION"," EXT");
&prefix.address1=tranwrd(&prefix.address1," FALLS"," FLS");
&prefix.address1=tranwrd(&prefix.address1," FERRY"," FRY");
&prefix.address1=tranwrd(&prefix.address1," FIELD"," FLD");
&prefix.address1=tranwrd(&prefix.address1," FLATS"," FLT");
&prefix.address1=tranwrd(&prefix.address1," FORD"," FRD");
&prefix.address1=tranwrd(&prefix.address1," FOREST"," FRST");
&prefix.address1=tranwrd(&prefix.address1," FORGE"," FRG");
&prefix.address1=tranwrd(&prefix.address1," FORK"," FRK");
&prefix.address1=tranwrd(&prefix.address1," FORT"," FT");
&prefix.address1=tranwrd(&prefix.address1," FREEWAY"," FWY");
&prefix.address1=tranwrd(&prefix.address1," GARDEN"," GDN");
&prefix.address1=tranwrd(&prefix.address1," GATEWAY"," GTWY");
&prefix.address1=tranwrd(&prefix.address1," GLEN"," GLN");
&prefix.address1=tranwrd(&prefix.address1," GREEN"," GRN");
&prefix.address1=tranwrd(&prefix.address1," GROVE"," GRV");
&prefix.address1=tranwrd(&prefix.address1," HARBOR"," HBR");
&prefix.address1=tranwrd(&prefix.address1," HAVEN"," HVN");
&prefix.address1=tranwrd(&prefix.address1," HEIGHT"," HT");
&prefix.address1=tranwrd(&prefix.address1," HIGHWAY"," HWY");
&prefix.address1=tranwrd(&prefix.address1," HILL"," HL");
&prefix.address1=tranwrd(&prefix.address1," HOLLOW"," HOLW");
&prefix.address1=tranwrd(&prefix.address1," INLET"," INLT");
&prefix.address1=tranwrd(&prefix.address1," ISLAND"," IS");
&prefix.address1=tranwrd(&prefix.address1," JUNCTION"," JCT");
&prefix.address1=tranwrd(&prefix.address1," KEY"," KY");
&prefix.address1=tranwrd(&prefix.address1," KNOLL"," KNL");
&prefix.address1=tranwrd(&prefix.address1," LAKE"," LK");
&prefix.address1=tranwrd(&prefix.address1," LANDING"," LNDG");
&prefix.address1=tranwrd(&prefix.address1," LANE"," LN");
&prefix.address1=tranwrd(&prefix.address1," LIGHT"," LGT");
&prefix.address1=tranwrd(&prefix.address1," LOAF"," LF");
&prefix.address1=tranwrd(&prefix.address1," LOCK"," LCK");
&prefix.address1=tranwrd(&prefix.address1," LODGE"," LDG");
&prefix.address1=tranwrd(&prefix.address1," MANOR"," MNR");
&prefix.address1=tranwrd(&prefix.address1," MEADOW"," MDW");
&prefix.address1=tranwrd(&prefix.address1," MILL"," ML");
&prefix.address1=tranwrd(&prefix.address1," MISSION"," MSN");
&prefix.address1=tranwrd(&prefix.address1," MOUNTAIN"," MTN");
&prefix.address1=tranwrd(&prefix.address1," MOUNT"," MT");
&prefix.address1=tranwrd(&prefix.address1," NECK"," NCK");
&prefix.address1=tranwrd(&prefix.address1," ORCHARD"," ORCH");
&prefix.address1=tranwrd(&prefix.address1," PARKWAY"," PKY");
&prefix.address1=tranwrd(&prefix.address1," PINES"," PNES");
&prefix.address1=tranwrd(&prefix.address1," PLACE"," PL");
&prefix.address1=tranwrd(&prefix.address1," PLAIN"," PLN");
&prefix.address1=tranwrd(&prefix.address1," PLAZA"," PLZ");
&prefix.address1=tranwrd(&prefix.address1," POINT"," PT");
&prefix.address1=tranwrd(&prefix.address1," PORT"," PRT");
&prefix.address1=tranwrd(&prefix.address1," PRAIRIE"," PR");
&prefix.address1=tranwrd(&prefix.address1," RADIAL"," RADL");
&prefix.address1=tranwrd(&prefix.address1," RANCH"," RNCH");
&prefix.address1=tranwrd(&prefix.address1," RAPID"," RPD");
&prefix.address1=tranwrd(&prefix.address1," REST"," RST");
&prefix.address1=tranwrd(&prefix.address1," RIDGE"," RDG");
&prefix.address1=tranwrd(&prefix.address1," RIVER"," RIV");
&prefix.address1=tranwrd(&prefix.address1," ROAD"," RD");
&prefix.address1=tranwrd(&prefix.address1," SHOAL"," SHL");
&prefix.address1=tranwrd(&prefix.address1," SHORE"," SHR");
&prefix.address1=tranwrd(&prefix.address1," SPRING"," SPG");
&prefix.address1=tranwrd(&prefix.address1," SQUARE"," SQ");
&prefix.address1=tranwrd(&prefix.address1," STATION"," STA");
&prefix.address1=tranwrd(&prefix.address1," STRAVENUE"," STRA");
&prefix.address1=tranwrd(&prefix.address1," STREAM"," STRM");
&prefix.address1=tranwrd(&prefix.address1," STREET"," ST");
&prefix.address1=tranwrd(&prefix.address1," SUMMIT"," SMT");
&prefix.address1=tranwrd(&prefix.address1," TERRACE"," TER");
&prefix.address1=tranwrd(&prefix.address1," TRACE"," TRCE");
&prefix.address1=tranwrd(&prefix.address1," TRACK"," TRAK");
&prefix.address1=tranwrd(&prefix.address1," TRAILER"," TRLR");
&prefix.address1=tranwrd(&prefix.address1," TRAIL"," TRL");
&prefix.address1=tranwrd(&prefix.address1," TUNNEL"," TUNL");
&prefix.address1=tranwrd(&prefix.address1," TURNPIKE"," TPKE");
&prefix.address1=tranwrd(&prefix.address1," UNION"," UN");
&prefix.address1=tranwrd(&prefix.address1," VALLEY"," VLY");
&prefix.address1=tranwrd(&prefix.address1," VIADUCT"," VIA");
&prefix.address1=tranwrd(&prefix.address1," VIEW"," VW");
&prefix.address1=tranwrd(&prefix.address1," VILLAGE"," VLG");
&prefix.address1=tranwrd(&prefix.address1," VILLE"," VL");
&prefix.address1=tranwrd(&prefix.address1," VISTA"," VIS");
&prefix.address1=tranwrd(&prefix.address1," WELLS"," WLS");

if scan(&prefix.address1,-1) in ('AV','CR','WY') and scan(&prefix.address1,3) ne '' then do;
		 if scan(&prefix.address1,-1)='AV' then &prefix.address1=substr(&prefix.address1,1,length(&prefix.address1)-2)||'AVE';
	else if scan(&prefix.address1,-1)='CR' then &prefix.address1=substr(&prefix.address1,1,length(&prefix.address1)-2)||'CIR';
	else if scan(&prefix.address1,-1)='WY' then &prefix.address1=substr(&prefix.address1,1,length(&prefix.address1)-2)||'WAY';
end;

&prefix.address1=tranwrd(&prefix.address1," NORTH"," N");
&prefix.address1=tranwrd(&prefix.address1," SOUTH"," S");
&prefix.address1=tranwrd(&prefix.address1," EAST"," E");
&prefix.address1=tranwrd(&prefix.address1," WEST"," W");
&prefix.address1=tranwrd(&prefix.address1," NORTHEAST"," NE");
&prefix.address1=tranwrd(&prefix.address1," NORTHWEST"," NW");
&prefix.address1=tranwrd(&prefix.address1," SOUTHEAST"," SE");
&prefix.address1=tranwrd(&prefix.address1," SOUTHWEST"," SW");

&prefix.address1=tranwrd(&prefix.address1," N."," N ");
&prefix.address1=tranwrd(&prefix.address1," S."," S ");
&prefix.address1=tranwrd(&prefix.address1," E."," E ");
&prefix.address1=tranwrd(&prefix.address1," W."," W ");
&prefix.address1=tranwrd(&prefix.address1," NE."," NE ");
&prefix.address1=tranwrd(&prefix.address1," NW."," NW ");
&prefix.address1=tranwrd(&prefix.address1," SE."," SE ");
&prefix.address1=tranwrd(&prefix.address1," SW."," SW ");

&prefix.address1=tranwrd(&prefix.address1," APT"," ");
&prefix.address1=tranwrd(&prefix.address1," UNIT"," ");

&prefix.address1 = compbl(compress(&prefix.address1,"`~!@#$%^&*()-_+=\|][{}',.<>?/:;"));

&prefix.address1=tranwrd(&prefix.address1,"POBOX","PO BOX");
&prefix.address1=tranwrd(&prefix.address1,"P O BOX","PO BOX");

	if length(cats(&prefix.address1)) le 5 then &prefix.address1 = "";
	else do;
		if substr(&prefix.address1,1,3) = "BOX" then &prefix.address1 = "PO " || &prefix.address1;
		else if substr(&prefix.address1,1,2) = "PO" and substr(&prefix.address1,4,3) ne "BOX" then &prefix.address1 = "PO BOX" || substr(&prefix.address1,indexc(&prefix.address1,"0123456789"));
		else if substr(&prefix.address1,1,3) = "P O" and substr(&prefix.address1,5,3) ne "BOX" then &prefix.address1 = "PO BOX" || substr(&prefix.address1,indexc(&prefix.address1,"0123456789"));

		if substr(&prefix.address1,1,6) = "PO BOX" then do;
			if indexc(&prefix.address1,"0123456789")=0 or scan(substr(&prefix.address1,7),2) ne ''
			then &prefix.address1 = "";
		end;
	end;

end;

%mend edw_linking_cleaner_addr;
